# Generated by Django 4.1 on 2022-09-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.FloatField(verbose_name='Обьем'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
